// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Account
{
    public int AccountId { get; set; }

    public int RoleId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string FullName { get; set; }

    public string Avatar { get; set; }

    public string Gender { get; set; }

    public string PhoneNumber { get; set; }

    public DateTime DateOfBirth { get; set; }

    public DateTime CreatedDate { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Chat> Chats { get; set; } = new List<Chat>();

    public virtual Elderly Elderly { get; set; }

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    public virtual ICollection<Game> Games { get; set; } = new List<Game>();

    public virtual ICollection<GroupMember> GroupMembers { get; set; } = new List<GroupMember>();

    public virtual ICollection<LessonFeedback> LessonFeedbacks { get; set; } = new List<LessonFeedback>();

    public virtual ICollection<LessonHistory> LessonHistories { get; set; } = new List<LessonHistory>();

    public virtual ICollection<Lesson> Lessons { get; set; } = new List<Lesson>();

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual ICollection<Notification> Notifications { get; set; } = new List<Notification>();

    public virtual Professor Professor { get; set; }

    public virtual ICollection<ProfessorRating> ProfessorRatings { get; set; } = new List<ProfessorRating>();

    public virtual Role Role { get; set; }

    public virtual ICollection<VideoCall> VideoCallCallers { get; set; } = new List<VideoCall>();

    public virtual ICollection<VideoCall> VideoCallReceivers { get; set; } = new List<VideoCall>();
}