// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Activity
{
    public int ActivityId { get; set; }

    public int ElderlyId { get; set; }

    public string ActivityName { get; set; }

    public string ActivityDescription { get; set; }

    public string Status { get; set; }

    public virtual ICollection<ActivitySchedule> ActivitySchedules { get; set; } = new List<ActivitySchedule>();

    public virtual Elderly Elderly { get; set; }
}