// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Chat
{
    public int ChatId { get; set; }

    public int SenderId { get; set; }

    public int ReceiverId { get; set; }

    public bool IsGroup { get; set; }

    public string Status { get; set; }

    public virtual ICollection<Message> Messages { get; set; } = new List<Message>();

    public virtual Account Sender { get; set; }
}