// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Elderly
{
    public int ElderlyId { get; set; }

    public int AccountId { get; set; }

    public string Allergy { get; set; }

    public string LivingSituation { get; set; }

    public decimal Weight { get; set; }

    public decimal Height { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<EmergencyContact> EmergencyContacts { get; set; } = new List<EmergencyContact>();

    public virtual ICollection<HealthIndicator> HealthIndicators { get; set; } = new List<HealthIndicator>();

    public virtual ICollection<Iotdevice> Iotdevices { get; set; } = new List<Iotdevice>();

    public virtual ICollection<Medication> Medications { get; set; } = new List<Medication>();

    public virtual ICollection<ProfessorAppointment> ProfessorAppointments { get; set; } = new List<ProfessorAppointment>();
}