// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Game
{
    public int GameId { get; set; }

    public int AccountId { get; set; }

    public string GameName { get; set; }

    public string GameDescription { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }
}