// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class GroupMember
{
    public int GroupMemberId { get; set; }

    public int GroupId { get; set; }

    public int AccountId { get; set; }

    public bool IsCreator { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual Group Group { get; set; }
}