// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Iotdevice
{
    public int DeviceId { get; set; }

    public int ElderlyId { get; set; }

    public string DeviceName { get; set; }

    public string SerialNumber { get; set; }

    public DateTime? LastConnected { get; set; }

    public int? BatteryLevel { get; set; }

    public string Note { get; set; }

    public string Status { get; set; }

    public virtual Elderly Elderly { get; set; }
}