// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class LessonFeedback
{
    public int LessonFeedbackId { get; set; }

    public int LessonId { get; set; }

    public int AccountId { get; set; }

    public string FeedbackComment { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual Lesson Lesson { get; set; }
}