// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class MedicationHistory
{
    public int MedicationHistoryId { get; set; }

    public int MedicationScheduleId { get; set; }

    public DateOnly MissedDate { get; set; }

    public string Status { get; set; }

    public virtual MedicationSchedule MedicationSchedule { get; set; }
}