// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class MedicationSchedule
{
    public int MedicationScheduleId { get; set; }

    public int MedicationId { get; set; }

    public TimeOnly TimeOfDay { get; set; }

    public string Dosage { get; set; }

    public string Status { get; set; }

    public virtual Medication Medication { get; set; }

    public virtual ICollection<MedicationHistory> MedicationHistories { get; set; } = new List<MedicationHistory>();
}