// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class Professor
{
    public int ProfessorId { get; set; }

    public int AccountId { get; set; }

    public string Specialization { get; set; }

    public string ClinicAddress { get; set; }

    public decimal? ConsultationFee { get; set; }

    public int? ExperienceYears { get; set; }

    public decimal? Rating { get; set; }

    public string Qualification { get; set; }

    public string Knowledge { get; set; }

    public string Career { get; set; }

    public string Achievement { get; set; }

    public string Status { get; set; }

    public virtual Account Account { get; set; }

    public virtual ICollection<ProfessorRating> ProfessorRatings { get; set; } = new List<ProfessorRating>();

    public virtual ICollection<ProfessorSchedule> ProfessorSchedules { get; set; } = new List<ProfessorSchedule>();
}