// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Configuration;

namespace SE.Data.Models;

public partial class SeniorEssentialsContext : DbContext
{
    public SeniorEssentialsContext(DbContextOptions<SeniorEssentialsContext> options)
        : base(options)
    {
    }

    public SeniorEssentialsContext()
    {
    }

    public static string GetConnectionString(string connectionStringName)
    {
        var config = new ConfigurationBuilder()
            .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
            .AddJsonFile("appsettings.json")
            .Build();

        string connectionString = config.GetConnectionString(connectionStringName);
        return connectionString;
    }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer(GetConnectionString("DefaultConnection"));

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<Activity> Activities { get; set; }

    public virtual DbSet<ActivitySchedule> ActivitySchedules { get; set; }

    public virtual DbSet<Chat> Chats { get; set; }

    public virtual DbSet<Elderly> Elderlies { get; set; }

    public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }

    public virtual DbSet<Game> Games { get; set; }

    public virtual DbSet<Group> Groups { get; set; }

    public virtual DbSet<GroupMember> GroupMembers { get; set; }

    public virtual DbSet<HealthIndicator> HealthIndicators { get; set; }

    public virtual DbSet<Iotdevice> Iotdevices { get; set; }

    public virtual DbSet<Lesson> Lessons { get; set; }

    public virtual DbSet<LessonFeedback> LessonFeedbacks { get; set; }

    public virtual DbSet<LessonHistory> LessonHistories { get; set; }

    public virtual DbSet<Medication> Medications { get; set; }

    public virtual DbSet<MedicationHistory> MedicationHistories { get; set; }

    public virtual DbSet<MedicationSchedule> MedicationSchedules { get; set; }

    public virtual DbSet<Message> Messages { get; set; }

    public virtual DbSet<Notification> Notifications { get; set; }

    public virtual DbSet<Professor> Professors { get; set; }

    public virtual DbSet<ProfessorAppointment> ProfessorAppointments { get; set; }

    public virtual DbSet<ProfessorRating> ProfessorRatings { get; set; }

    public virtual DbSet<ProfessorSchedule> ProfessorSchedules { get; set; }

    public virtual DbSet<Role> Roles { get; set; }

    public virtual DbSet<VideoCall> VideoCalls { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountId).HasName("PK__Account__349DA5A65DDF59B6");

            entity.ToTable("Account");

            entity.Property(e => e.Avatar).IsRequired();
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DateOfBirth).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.FullName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Gender)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.PhoneNumber)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Role).WithMany(p => p.Accounts)
                .HasForeignKey(d => d.RoleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Account__RoleId__398D8EEE");
        });

        modelBuilder.Entity<Activity>(entity =>
        {
            entity.HasKey(e => e.ActivityId).HasName("PK__Activity__45F4A7916E911F58");

            entity.ToTable("Activity");

            entity.Property(e => e.ActivityDescription).HasMaxLength(100);
            entity.Property(e => e.ActivityName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Elderly).WithMany(p => p.Activities)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Activity__Elderl__02084FDA");
        });

        modelBuilder.Entity<ActivitySchedule>(entity =>
        {
            entity.HasKey(e => e.ActivityScheduleId).HasName("PK__Activity__273CEBBFE5534ACF");

            entity.ToTable("ActivitySchedule");

            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Activity).WithMany(p => p.ActivitySchedules)
                .HasForeignKey(d => d.ActivityId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__ActivityS__Activ__04E4BC85");
        });

        modelBuilder.Entity<Chat>(entity =>
        {
            entity.HasKey(e => e.ChatId).HasName("PK__Chat__A9FBE7C67518B540");

            entity.ToTable("Chat");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Sender).WithMany(p => p.Chats)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Chat__SenderId__778AC167");
        });

        modelBuilder.Entity<Elderly>(entity =>
        {
            entity.HasKey(e => e.ElderlyId).HasName("PK__Elderly__8E4AA95941111903");

            entity.ToTable("Elderly");

            entity.HasIndex(e => e.AccountId, "UQ__Elderly__349DA5A7DF9D88A9").IsUnique();

            entity.Property(e => e.Allergy).HasMaxLength(50);
            entity.Property(e => e.Height).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.LivingSituation).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Account).WithOne(p => p.Elderly)
                .HasForeignKey<Elderly>(d => d.AccountId)
                .HasConstraintName("FK__Elderly__Account__3D5E1FD2");
        });

        modelBuilder.Entity<EmergencyContact>(entity =>
        {
            entity.HasKey(e => e.EmergencyContactId).HasName("PK__Emergenc__E8A61D8E596163A4");

            entity.ToTable("EmergencyContact");

            entity.Property(e => e.ContactName).HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Emergency__Accou__6E01572D");

            entity.HasOne(d => d.Elderly).WithMany(p => p.EmergencyContacts)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Emergency__Elder__6D0D32F4");
        });

        modelBuilder.Entity<Game>(entity =>
        {
            entity.HasKey(e => e.GameId).HasName("PK__Game__2AB897FDF7524E21");

            entity.ToTable("Game");

            entity.Property(e => e.GameDescription).HasMaxLength(100);
            entity.Property(e => e.GameName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.Games)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Game__AccountId__5441852A");
        });

        modelBuilder.Entity<Group>(entity =>
        {
            entity.HasKey(e => e.GroupId).HasName("PK__Group__149AF36AF14A1915");

            entity.ToTable("Group");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.GroupName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<GroupMember>(entity =>
        {
            entity.HasKey(e => e.GroupMemberId).HasName("PK__GroupMem__344812927AFF7797");

            entity.ToTable("GroupMember");

            entity.HasIndex(e => new { e.GroupId, e.AccountId }, "UQ__GroupMem__67D329314F04B128").IsUnique();

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GroupMemb__Accou__74AE54BC");

            entity.HasOne(d => d.Group).WithMany(p => p.GroupMembers)
                .HasForeignKey(d => d.GroupId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__GroupMemb__Group__73BA3083");
        });

        modelBuilder.Entity<HealthIndicator>(entity =>
        {
            entity.HasKey(e => e.HealthIndicatorId).HasName("PK__HealthIn__FF9AABEA770A0327");

            entity.ToTable("HealthIndicator");

            entity.Property(e => e.BloodPressureDiastolic).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.BloodPressureSystolic).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.BloodSugar).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.BodyTemperature).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.DateRecorded).HasColumnType("datetime");
            entity.Property(e => e.Height).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Weight).HasColumnType("decimal(10, 2)");

            entity.HasOne(d => d.Elderly).WithMany(p => p.HealthIndicators)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__HealthInd__Elder__619B8048");
        });

        modelBuilder.Entity<Iotdevice>(entity =>
        {
            entity.HasKey(e => e.DeviceId).HasName("PK__IOTDevic__49E123114B35BC67");

            entity.ToTable("IOTDevice");

            entity.Property(e => e.DeviceName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.LastConnected).HasColumnType("datetime");
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.SerialNumber).HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Elderly).WithMany(p => p.Iotdevices)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__IOTDevice__Elder__46E78A0C");
        });

        modelBuilder.Entity<Lesson>(entity =>
        {
            entity.HasKey(e => e.LessonId).HasName("PK__Lesson__B084ACD05BD2A948");

            entity.ToTable("Lesson");

            entity.Property(e => e.LessonDescription).HasMaxLength(100);
            entity.Property(e => e.LessonName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.Lessons)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Lesson__AccountI__571DF1D5");
        });

        modelBuilder.Entity<LessonFeedback>(entity =>
        {
            entity.HasKey(e => e.LessonFeedbackId).HasName("PK__LessonFe__2E315845A127DD9B");

            entity.ToTable("LessonFeedback");

            entity.Property(e => e.FeedbackComment).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.LessonFeedbacks)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LessonFee__Accou__5EBF139D");

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonFeedbacks)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LessonFee__Lesso__5DCAEF64");
        });

        modelBuilder.Entity<LessonHistory>(entity =>
        {
            entity.HasKey(e => e.LessonHistoryId).HasName("PK__LessonHi__D3775A59A235A508");

            entity.ToTable("LessonHistory");

            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.LessonHistories)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LessonHis__Accou__5AEE82B9");

            entity.HasOne(d => d.Lesson).WithMany(p => p.LessonHistories)
                .HasForeignKey(d => d.LessonId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__LessonHis__Lesso__59FA5E80");
        });

        modelBuilder.Entity<Medication>(entity =>
        {
            entity.HasKey(e => e.MedicationId).HasName("PK__Medicati__62EC1AFA4E9C9672");

            entity.ToTable("Medication");

            entity.Property(e => e.Content).HasMaxLength(50);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DateFrequency).HasMaxLength(50);
            entity.Property(e => e.Dosage).HasMaxLength(20);
            entity.Property(e => e.FrequencyType).HasMaxLength(20);
            entity.Property(e => e.MedicationName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Note).HasMaxLength(255);
            entity.Property(e => e.Shape).HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.TimeFrequency).HasMaxLength(50);

            entity.HasOne(d => d.Elderly).WithMany(p => p.Medications)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medicatio__Elder__6477ECF3");
        });

        modelBuilder.Entity<MedicationHistory>(entity =>
        {
            entity.HasKey(e => e.MedicationHistoryId).HasName("PK__Medicati__6EB20B7F3A7D8073");

            entity.ToTable("MedicationHistory");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.MedicationSchedule).WithMany(p => p.MedicationHistories)
                .HasForeignKey(d => d.MedicationScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medicatio__Medic__6A30C649");
        });

        modelBuilder.Entity<MedicationSchedule>(entity =>
        {
            entity.HasKey(e => e.MedicationScheduleId).HasName("PK__Medicati__EDCDE99C50E6B191");

            entity.ToTable("MedicationSchedule");

            entity.Property(e => e.Dosage)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Medication).WithMany(p => p.MedicationSchedules)
                .HasForeignKey(d => d.MedicationId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Medicatio__Medic__6754599E");
        });

        modelBuilder.Entity<Message>(entity =>
        {
            entity.HasKey(e => e.MessageId).HasName("PK__Message__C87C0C9C4077FC9E");

            entity.ToTable("Message");

            entity.Property(e => e.MessageContent).IsRequired();
            entity.Property(e => e.SendTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Chat).WithMany(p => p.Messages)
                .HasForeignKey(d => d.ChatId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Message__ChatId__7A672E12");

            entity.HasOne(d => d.Sender).WithMany(p => p.Messages)
                .HasForeignKey(d => d.SenderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Message__SenderI__7B5B524B");
        });

        modelBuilder.Entity<Notification>(entity =>
        {
            entity.HasKey(e => e.NotificationId).HasName("PK__Notifica__20CF2E1258EB98E5");

            entity.ToTable("Notification");

            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Message).HasMaxLength(255);
            entity.Property(e => e.NotificationType)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);

            entity.HasOne(d => d.Account).WithMany(p => p.Notifications)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Notificat__Accou__440B1D61");
        });

        modelBuilder.Entity<Professor>(entity =>
        {
            entity.HasKey(e => e.ProfessorId).HasName("PK__Professo__900359495C78486B");

            entity.ToTable("Professor");

            entity.HasIndex(e => e.AccountId, "UQ__Professo__349DA5A7637633ED").IsUnique();

            entity.Property(e => e.ClinicAddress).HasMaxLength(100);
            entity.Property(e => e.ConsultationFee).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Rating).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithOne(p => p.Professor)
                .HasForeignKey<Professor>(d => d.AccountId)
                .HasConstraintName("FK__Professor__Accou__412EB0B6");
        });

        modelBuilder.Entity<ProfessorAppointment>(entity =>
        {
            entity.HasKey(e => e.ProfessorAppointmentId).HasName("PK__Professo__CBB3A52E0FF5D04F");

            entity.ToTable("ProfessorAppointment");

            entity.Property(e => e.AppointmentTime).HasColumnType("datetime");
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Elderly).WithMany(p => p.ProfessorAppointments)
                .HasForeignKey(d => d.ElderlyId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__Elder__4CA06362");

            entity.HasOne(d => d.ProfessorSchedule).WithMany(p => p.ProfessorAppointments)
                .HasForeignKey(d => d.ProfessorScheduleId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__Profe__4D94879B");
        });

        modelBuilder.Entity<ProfessorRating>(entity =>
        {
            entity.HasKey(e => e.ProfessorRatingId).HasName("PK__Professo__4B8DB8B310E2BE10");

            entity.ToTable("ProfessorRating");

            entity.Property(e => e.Rating).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.RatingComment).HasMaxLength(255);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Account).WithMany(p => p.ProfessorRatings)
                .HasForeignKey(d => d.AccountId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__Accou__5165187F");

            entity.HasOne(d => d.Professor).WithMany(p => p.ProfessorRatings)
                .HasForeignKey(d => d.ProfessorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__Profe__5070F446");
        });

        modelBuilder.Entity<ProfessorSchedule>(entity =>
        {
            entity.HasKey(e => e.ProfessorScheduleId).HasName("PK__Professo__A283D5B428536E24");

            entity.ToTable("ProfessorSchedule");

            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Professor).WithMany(p => p.ProfessorSchedules)
                .HasForeignKey(d => d.ProfessorId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Professor__Profe__49C3F6B7");
        });

        modelBuilder.Entity<Role>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK__Role__8AFACE1AF7EE5C93");

            entity.ToTable("Role");

            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<VideoCall>(entity =>
        {
            entity.HasKey(e => e.VideoCallId).HasName("PK__VideoCal__2900263289736F0B");

            entity.ToTable("VideoCall");

            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20);

            entity.HasOne(d => d.Caller).WithMany(p => p.VideoCallCallers)
                .HasForeignKey(d => d.CallerId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VideoCall__Calle__7E37BEF6");

            entity.HasOne(d => d.Receiver).WithMany(p => p.VideoCallReceivers)
                .HasForeignKey(d => d.ReceiverId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__VideoCall__Recei__7F2BE32F");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}