// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE.Data.Models;

public partial class VideoCall
{
    public int VideoCallId { get; set; }

    public int CallerId { get; set; }

    public int ReceiverId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Status { get; set; }

    public virtual Account Caller { get; set; }

    public virtual Account Receiver { get; set; }
}